name : build and test

on: push


jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                runs-on: [ubuntu-latest]
                compiler: ["clang-6.0","clang-7","clang-8","clang-9","clang-10","clang-11","g++-7","g++-8","g++-9","g++-10"]
        runs-on: ${{ matrix.runs-on }}
        env:
            CXX: ${{ matrix.compiler }}
        steps:
        - id: step0
          name: CHeckout code
          uses: actions/checkout@v2
        - id: fetch_build_tools
          run: |
              sudo apt install cmake build-essential -y libboost-all-dev ${{ matrix.compiler }}
        - id: build
          if: startsWith(matrix.compiler, 'clang')
          run: |
              CXX=clang++ ./build.sh -j`nproc`
              ./build.sh test
        - id: build_test
          if: startsWith(matrix.compiler, 'g++')
          run: |
              ./build.sh -j`nproc`
              ./build.sh test
